export const religiousSndSpiritual = [
	{ name: 'Acts College Ministry', booth: 'A1' },
	{ name: 'Acts2fellowship', booth: 'A2' },
	{ name: 'Asian American Christian Fellowship', booth: 'A3' },
	{ name: 'Be Known Movement at UCI', booth: 'A4' },
	{ name: 'Berean Christian Club', booth: 'A5' },
	{ name: 'Bethel Grace Church', booth: 'A6' },
	{ name: 'Christian Students', booth: 'A7' },
	{ name: 'Community Table', booth: 'A8' },
	{ name: 'CrossLife College Fellowship', booth: 'A9' },
	{ name: 'Cru', booth: 'A10' },
	{ name: 'Delight Ministries', booth: 'A11' },
	{ name: 'Destino at UCI', booth: 'A12' },
	{ name: 'Filipino Catholic Community - Liwanag', booth: 'A13' },
	{ name: 'Hearts Openly Praying Everywhere', booth: 'A14' },
	{ name: 'Gathering Rejoicing One in Worship', booth: 'A15' },
	{ name: 'Global Medical Missions Alliance', booth: 'A16' },
	{ name: 'GoodSoil at UCI', booth: 'A17' },
	{ name: 'Hillel at UC Irvine', booth: 'A18' },
	{ name: 'International Student Gathering', booth: 'A19' },
	{ name: 'InterVarsity Christian Fellowship (IVCF)', booth: 'A20' },
	{ name: 'Kristos Campus Missions', booth: 'A21' },
	{ name: 'Living Stone Christian Fellowship', booth: 'A22' },
	{ name: 'Living Water College Ministry', booth: 'A23' },
	{ name: 'Mariners at UCI', booth: 'A24' },
	{ name: 'Muslim Student Union', booth: 'A25' },
	{ name: 'Navigators', booth: 'A26' },
	{ name: 'New Life Fellowship', booth: 'A27' },
	{ name: 'Overflow Campus Fellowship', booth: 'A28' },
	{ name: 'Reformed University Fellowship', booth: 'A29' },
	{ name: 'Seed Fellowship', booth: 'A30' },
	{ name: 'Sikh Student Association', booth: 'A31' },
	{ name: 'Soon Movement', booth: 'A32' }
];

export const multicultural = [
	{ name: 'Afghan United Association', booth: 'B33' },
	{ name: 'Alpha Epsilon Omega Fraternity, Gamma Chapter', booth: 'B34' },
	{ name: 'Alpha Gamma Alpha, Inc', booth: 'B35' },
	{ name: 'Armenian Students Association (ASA)', booth: 'B36' },
	{ name: 'Bangladeshi Student Association- BSA', booth: 'B37' },
	{ name: 'Black Student Union', booth: 'B38' },
	{ name: 'Bridges International', booth: 'B39' },
	{ name: 'Burmese Student Association', booth: 'B40' },
	{ name: 'Cambodian Awareness Organization', booth: 'B41' },
	{ name: 'Chinese Association', booth: 'B42' },
	{ name: 'Chinese Students and Scholars Association', booth: 'B43' },
	{ name: 'Club Italia at UCI', booth: 'B44' },
	{ name: 'Communication Club', booth: 'B45' },
	{ name: 'Filipinx Undergraduate Scientists-Engineers in an Organized Network', booth: 'B46' },
	{ name: 'French and Francophone Club', booth: 'B47' },
	{ name: 'Hansori', booth: 'B48' },
	{ name: 'Hermanas Unidas de UCI', booth: 'B49' },
	{ name: 'Hmong Student Association', booth: 'B50' },
	{ name: 'Hong Kong Student Union', booth: 'B51' },
	{ name: 'Indian Sub-Continental Club', booth: 'B52' },
	{ name: 'Japanese Student Association', booth: 'B53' },
	{ name: 'Kababayan', booth: 'B54' },
	{ name: 'Kappa Zeta Phi', booth: 'B55' },
	{ name: 'Korean American Student Association', booth: 'B56' },
	{ name: 'Language and Linguistics Club', booth: 'B57' },
	{ name: 'Na `Opio O Ka Aina` - Hawai’i Club', booth: 'B58' },
	{ name: 'La Familia de UCI', booth: 'B59' },
	{ name: 'Nigerian Student Association', booth: 'I71' },
	{ name: 'Pilipinx Pre-Health Undergraduate Student Organization', booth: 'I72' },
	{ name: 'Pilipinx-Americans in Social Studies', booth: 'I73' },
	{ name: 'Pre-Law Latinx Association', booth: 'I74' },
	{ name: 'Society of Arab Students', booth: 'I75' },
	{ name: 'Southeast Asian Student Association', booth: 'I76' },
	{ name: 'Students Advocating For Immigrant Rights and Equity', booth: 'I77' },
	{ name: 'Taiwan National Organization', booth: 'I78' },
	{ name: 'Taiwanese American Organization (TAO)', booth: 'I79' },
	{ name: 'Thai Culture Association', booth: 'I80' },
	{ name: 'Tomo No Kai', booth: 'I81' },
	{ name: 'UMOJA Community Org', booth: 'I82' },
	{ name: 'Vietnamese Student Association', booth: 'I83' },
	{ name: 'Pacific Islander Student Association', booth: 'E310' }
];

export const creativeArts = [
	{ name: 'Animation Anteaters', booth: 'B60' },
	{ name: 'Anteaters Student Audio Production', booth: 'B61' },
	{ name: 'Art Club Collective', booth: 'B62' },
	{ name: 'Art History Undergraduate Association', booth: 'B63' },
	{ name: 'Echolalia', booth: 'B64' },
	{ name: 'Euphonic Video Game Ensemble at UCI', booth: 'B65' },
	{ name: 'FADA Film Arts Drama Alliance Network', booth: 'B66' },
	{ name: 'Goth Club at UCI', booth: 'B67' },
	{ name: 'Her Campus', booth: 'B68' },
	{ name: 'Metro Theatre Company', booth: 'B69' },
	{ name: 'Voces', booth: 'B70' }
];

export const academicsAndHonors = [
	{ name: 'Undergraduate Mathematics Committee', booth: 'C342' },
	{ name: 'Alpha Epsilon Delta PreHealth Honor Society - AED', booth: 'C343' },
	{ name: 'Association for Computing Machinery', booth: 'C344' },
	{ name: 'BioSci International Student Association', booth: 'C345' },
	{ name: 'Chinese Union in Computer Science', booth: 'C346' },
	{ name: 'Cognitive Science Association', booth: 'C347' },
	{ name: 'Delta Epsilon Mu', booth: 'C348' },
	{ name: 'Biological Sciences Student Council (BSC)', booth: 'C349' },
	{ name: 'Future Business Leaders of America', booth: 'C350' },
	{ name: 'Developer Student Club at UCI', booth: 'C351' },
	{ name: 'Eta Sigma Phi at UCI', booth: 'C352' },
	{ name: 'IMED at UCI - FIMRC affiliated', booth: 'C353' },
	{ name: 'Global Health Research Education And Translation Club', booth: 'C354' },
	{ name: 'Quantum Computing Club at UCI', booth: 'C355' },
	{ name: 'Tau Beta Pi (National Engineering Honor Society)', booth: 'C356' },
	{ name: 'Human Biology Club at UCI', booth: 'C357' },
	{ name: 'Management Information Student Society at UCI - MAISS', booth: 'C358' },
	{ name: 'Latinx Student Psychological Association', booth: 'C359' },
	{ name: 'Merage Undergraduate Student Association (MUSA)', booth: 'C360' },
	{ name: 'Model United Nations (MUN)', booth: 'C361' },
	{ name: 'NORD Students for Rare Chapter at UCI', booth: 'C362' },
	{ name: 'Nu Rho Psi at UCI', booth: 'C363' },
	{ name: 'Nursing Science Student Association', booth: 'C364' },
	{ name: 'Phi Delta Epsilon Medical Fraternity - CA Epsilon', booth: 'C365' },
	{ name: 'Psi Chi at UC Irvine', booth: 'C366' },
	{ name: 'Psychology Student Association', booth: 'C367' },
	{ name: 'Research Outreach at UCI', booth: 'C368' },
	{ name: 'Theta Tau', booth: 'C369' },
	{ name: 'Women in CyberSecurity Student Chapter at UCI - WiCyS', booth: 'C370' },
	{ name: 'Women in Information and Computer Sciences', booth: 'C371' },
	{ name: 'Anthology Yearbook', booth: 'C372' },
	{ name: 'ATV - Anteater TV', booth: 'C373' },
	{ name: 'TGIF - The Green Initiative Fund', booth: 'C374' },
	{ name: 'The New University', booth: 'C735' },
	{ name: 'International Student Excellence Programs', booth: 'C376' },
	{ name: 'The Divison of Student Affairs', booth: 'C377-378' },
	{ name: 'All of Us Research Program', booth: 'C379' },
	{ name: 'ANTrepeneur Center', booth: 'C380' },
	{ name: 'Campus Representatives', booth: 'C381' },
	{ name: 'Basic Needs Center', booth: 'C382' },
	{ name: 'Center for Black Cultures, Resources & Research', booth: 'C383' },
	{ name: 'Center for Student Leadership', booth: 'C384' },
	{ name: 'Cross-Cultural Center', booth: 'C385' },
	{ name: 'UCI Dream Center', booth: 'C386' },
	{ name: 'Emergency Management', booth: 'C387-389' },
	{ name: 'International Center', booth: 'C390' },
	{ name: 'UCI Latinx Resource Center', booth: 'C391' },
	{ name: 'Student Outreach & Retention Center', booth: 'C392' },
	{ name: 'Sustainability Resource Center', booth: 'C393' },
	{ name: 'Womxn’s Center for Success', booth: 'C394' },
	{ name: 'Center for Excellence in Writing & Communication', booth: 'C395' },
	{ name: 'Center for Investment & Wealth Management', booth: 'C396' },
	{ name: 'UCI Transportation', booth: 'C397-398' },
	{ name: 'Classics', booth: 'C399' },
	{ name: 'CP-LEADS Fellows Program at UCI School of Education', booth: 'C400' },
	{ name: 'Division of Career Pathways', booth: 'C401' },
	{ name: 'ICS Office of Outreach, Access, and Inclusion', booth: 'C402' },
	{ name: 'Langson Institute and Museum of California Art', booth: 'C403' },
	{ name: 'KUCI 88.9 fm', booth: 'C404' },
	{ name: 'Merage School of Business Masters Programs', booth: 'C405' },
	{ name: 'Office of Civic Engagement', booth: 'C406' },
	{ name: 'Public Health Informatics & Technology (PHIT) Program', booth: 'C407' },
	{ name: 'Stella Zhang New Venture Competition - Beall Center', booth: 'C408' },
	{ name: 'Study Abroad Center', booth: 'C409' },
	{ name: 'Student Center & Event Services', booth: 'C410' },
	{ name: 'The Scholarship Opportunities Program', booth: 'C411' },
	{ name: 'UC PRIME Pre-Health Pathways', booth: 'C412' },
	{ name: 'UCI CARE', booth: 'C413' },
	{ name: 'UCI Police Department', booth: 'C414' },
	{ name: 'UCI Scholarships', booth: 'C415' },
	{ name: 'Undergraduate Research Opportunities Program (UROP)', booth: 'C416' },
	{ name: 'Blood Donor Center', booth: 'C417' },
	{ name: 'UCI Program in Public Health', booth: 'C418' },
	{ name: 'Intercollegiate Athletics', booth: 'F283-285' },
	{ name: 'UCI Dining', booth: 'E311-314' },
	{ name: 'ASUCI Esecutive Offices', booth: 'E-ASUC' }
];

export const sororityAndFraternityLife = [
	{ name: 'Sigma Lambda Gamma National Sorority Inc.', booth: 'D315' },
	{ name: 'La Unidad Latina, Lambda Upsilon Lambda Fraternity, Inc.', booth: 'D316' },
	{ name: 'Phi Lambda Rho Sorority, Inc.', booth: 'D317' },
	{ name: 'Nu Alpha Kappa Fraternity, Inc.', booth: 'D318' },
	{ name: 'Sigma Pi Alpha Sorority, Inc.', booth: 'D319' },
	{ name: 'Multicultural Sorority & Fraternity Council (MSFC)', booth: 'D320' },
	{ name: 'Lambda Theta Delta', booth: 'D321' },
	{ name: 'Phi Zeta Tau', booth: 'D322' },
	{ name: 'alpha Kappa Delta Phi - aKDPhi', booth: 'D323' },
	{ name: 'Delta Lambda Chi', booth: 'D324' },
	{ name: 'Alpha Chi Omega', booth: 'D325' },
	{ name: 'Delta Delta Delta (Tri Delta)', booth: 'D326' },
	{ name: 'Pi Beta Phi (Pi Phi)', booth: 'D327' },
	{ name: 'Panhellenic Association at UCI', booth: 'D328' },
	{ name: 'Gamma Phi Beta (Gamma Phi)', booth: 'D329' },
	{ name: 'Delta Gamma', booth: 'D330' },
	{ name: 'Kappa Alpha Theta (Theta)', booth: 'D331' },
	{ name: 'Phi Sigma Rho', booth: 'D332' },
	{ name: 'Triangle Fraternity', booth: 'D333' },
	{ name: 'Sigma Phi Epsilon (SigEp)', booth: 'D334' },
	{ name: 'Kappa Sigma (Kappa Sig)', booth: 'D335' },
	{ name: 'Phi Delta Theta Fraternity', booth: 'D336' },
	{ name: 'Sigma Chi', booth: 'D337' },
	{ name: 'Alpha Phi Epsilon (AEPi)', booth: 'D338' },
	{ name: 'Sigma Nu', booth: 'D339' },
	{ name: 'Alpha Sigma Phi', booth: 'D340' },
	{ name: 'Sigma Pi', booth: 'D341' }
];

export const performanceAndEntertainment = [
	{ name: 'Aerodynamix', booth: 'E291' },
	{ name: 'Acappella', booth: 'E292' },
	{ name: 'Ballet Folklorico de UCI', booth: 'E293' },
	{ name: 'Chinese Orchestra@UC Irvine', booth: 'E294' },
	{ name: 'Circle of Fifths', booth: 'E295' },
	{ name: 'Clair De Lune A Cappella', booth: 'E296' },
	{ name: 'Haath A Cappella', booth: 'E297' },
	{ name: 'Improv Revolution', booth: 'E298' },
	{ name: 'INSA Dance Team', booth: 'E299' },
	{ name: 'Jodaiko (Taiko Drumming Ensemble)', booth: 'E300' },
	{ name: 'Kaba Modern', booth: 'E301' },
	{ name: 'KKAP K-pop Dance Team', booth: 'E302' },
	{ name: 'Magic and More at UCI', booth: 'E303' },
	{ name: 'Musical Improv Collective', booth: 'E304' },
	{ name: 'Open Jam', booth: 'E305' },
	{ name: 'Uniting Voices', booth: 'E306' },
	{ name: 'Vermillion Vocalists', booth: 'E307' },
	{ name: 'Vocalotus A Cappella', booth: 'E308' },
	{ name: 'Zamana at UCI', booth: 'E309' }
];

export const clubSportsAndFitness = [
	{ name: 'Badminton Club at UCI', booth: 'F130' },
	{ name: 'Brazilian Jiu Jitsu Club at UCI', booth: 'F131' },
	{ name: 'Climbing Club at UCI', booth: 'F132' },
	{ name: 'Club Baseball at UCI', booth: 'F133' },
	{ name: 'Club Softball at UCI', booth: 'F134' },
	{ name: 'Cycling Club at UCI', booth: 'F135' },
	{ name: 'Dragon Boat at UC Irvine', booth: 'F136' },
	{ name: 'Fencing Club at UCI', booth: 'F137' },
	{ name: 'Kendo Club at UCI', booth: 'F138' },
	{ name: 'Sailing Club at UCI', booth: 'F139' },
	{ name: "Men's Club Volleyball at UCI", booth: 'F140' },
	{ name: "Women's Volleyball Club", booth: 'F141' },
	{ name: "Men's Club Water Polo at UCI", booth: 'F142' },
	{ name: "Women's Water Polo Club at UCI", booth: 'F143' },
	{ name: "Men's Lacrosse Club at UCI", booth: 'F144' },
	{ name: "Women's Lacrosse Club at UCI", booth: 'F145' },
	{ name: "Men's Rowing Club at UCI", booth: 'F146' },
	{ name: "Men's Ultimate Frisbee Club at UCI", booth: 'F147' },
	{ name: "Women's Ultimate Club (formerly Women's Ultimate Frisbee Club at UCI)", booth: 'F148' },
	{ name: 'Nihon Karate Club at UCI', booth: 'F149' },
	{ name: 'Running Club at UCI', booth: 'F150' },
	{ name: 'Swim Club at UCI', booth: 'F151' },
	{ name: 'Taekwondo at UCI', booth: 'F152' },
	{ name: 'Triathlon Club at UCI', booth: 'F153' },
	{ name: "Women's Rugby Club at UCI", booth: 'F154' },
	{ name: "Women's Soccer Club", booth: 'F155' },
	{ name: 'Wushu Club at UCI', booth: 'F156' },
	{ name: 'Body Building Club at UCI', booth: 'F157' },
	{ name: 'Girl Gains', booth: 'F158' },
	{ name: "Women's Rowing Club at UCI", booth: 'F159' }
];

export const careerAndProfessional = [
	{ name: '180 Degrees Consulting at UC Irvine', booth: 'F160' },
	{ name: 'Accounting Association', booth: 'F161' },
	{ name: 'Alpha Kappa Psi', booth: 'F162' },
	{
		name: 'American Institute of Aeronautics and Astronautics Student Branch at UCI (AIAA)',
		booth: 'F163'
	},
	{ name: 'American Institute of Chemical Engineers', booth: 'F164' },
	{ name: 'American Medical Student Association at UCI', booth: 'F165' },
	{ name: "American Medical Women's Association Undergraduate Division at UCI", booth: 'F166' },
	{ name: 'American Society of Civil Engineers', booth: 'F167' },
	{ name: 'American Society of Mechanical Engineers at UCI', booth: 'F168' },
	{ name: 'Anteater Aviation', booth: 'F169' },
	{ name: 'Anteater Emergency Medical Services', booth: 'F170' },
	{ name: 'Anteater Moot Court', booth: 'F171' },
	{ name: 'Artificial Intelligence at UCI', booth: 'F172' },
	{ name: 'Asian Corporate & Entrepreneur Leaders', booth: 'F173' },
	{ name: 'Association of Latino Professionals for America', booth: 'F174' },
	{ name: 'Biomedical Engineering Society', booth: 'F175' },
	{ name: 'Black Law Society', booth: 'F176' },
	{ name: 'Black Psychology Student Association', booth: 'F177' },
	{ name: 'Bridging The Gap at UCI - BTG', booth: 'F178' },
	{ name: 'Business Careers in Entertainment Club at UCI', booth: 'F179' },
	{ name: 'CalTeach at UCI', booth: 'F180' },
	{ name: 'Chemistry Club at UCI', booth: 'F181' },
	{ name: 'Commit the Change', booth: 'F182' },
	{ name: 'Cosmetic Chemist Society', booth: 'F183' },
	{ name: 'Data @ UCI', booth: 'F184' },
	{ name: 'Delta Delta Sigma - Pre-Dental Fraternity', booth: 'F185' },
	{ name: 'Delta Sigma Pi', booth: 'F186' },
	{ name: 'Design at UCI', booth: 'F187' },
	{ name: 'Effective Altruism Club', booth: 'F188' },
	{ name: 'Engineering Student Council', booth: 'F189' },
	{ name: 'Engineers for a Sustainable World at UCI', booth: 'F190' },
	{ name: 'Engineers Without Borders', booth: 'F191' },
	{ name: 'Financial Literacy Association - FLA', booth: 'F192' },
	{ name: 'Forensic Club', booth: 'F193' },
	{ name: 'Global Medical Training at UCI', booth: 'F194' },
	{ name: 'Hack at UCI', booth: 'F195' },
	{ name: 'Hedge Fund Society', booth: 'F196' },
	{ name: 'Human Resources Management Association at UCI', booth: 'F197' },
	{ name: 'ICS Student Council (ICSSC)', booth: 'F198' },
	{ name: 'Institute of Transportation Engineers', booth: 'F199' },
	{ name: 'Irvine FinTech Association - IFA', booth: 'F200' },
	{ name: 'Irvine Investment and Trading Group', booth: 'F201' },
	{ name: 'Lambda Phi Nu', booth: 'F202' },
	{ name: 'Latino Business Student Association (LBSA)', booth: 'F203' },
	{ name: 'Legacy Robotics', booth: 'F204' },
	{ name: 'MAES Latinos in Science and Engineering', booth: 'F205' },
	{ name: 'Marketing Association (MA)', booth: 'F206' },
	{ name: 'Materials Science Club at UCI', booth: 'F207' },
	{ name: 'Math Finance Club - MFC', booth: 'F208' },
	{ name: 'Minority Association of PreHealth Students', booth: 'F209' },
	{ name: 'Mock Trial', booth: 'F210' },
	{ name: 'National Society of Black Engineers (NSBE)', booth: 'F211' },
	{ name: 'Pharmaceutical Sciences Alternative Careers Association', booth: 'F212' },
	{ name: 'Phi Chi Theta', booth: 'F213' },
	{ name: 'Physician Assistants Coming Together at UCI - PACT', booth: 'F214' },
	{ name: 'Pre-Dental Society at UC Irvine - PDS', booth: 'F215' },
	{ name: 'Pre-Health Alliance', booth: 'F216' },
	{ name: 'Pre-Law Society at UC Irvine', booth: 'F217' },
	{ name: 'Pre-Occupational Therapy Student Society', booth: 'F218' },
	{ name: 'Pre-Pharmacy Society (PPS) at UC Irvine', booth: 'F219' },
	{ name: 'Pre-Student Osteopathic Medical Association (Pre-SOMA)', booth: 'F220' },
	{ name: 'Pre-Veterinary and Animal Wellness Association (PAWA)', booth: 'F221' },
	{ name: 'Pro-Health Journal Club', booth: 'F222' },
	{ name: 'Product Association at UCI', booth: 'F223' },
	{ name: 'Real Estate Association at UCIREA', booth: 'F224' },
	{ name: 'Sigma Eta Pi - SEP', booth: 'F225' },
	{ name: 'Social Entrepreneurship Association', booth: 'F226' },
	{ name: 'Society of Hispanic Professional Engineers at UCI - SHPE', booth: 'F227' },
	{ name: 'Society of Women Engineers', booth: 'F228' },
	{ name: 'Sports Business Association - SBA', booth: 'F229' },
	{ name: 'Sports Medicine Club', booth: 'F230' },
	{ name: 'Student Alumni Association', booth: 'F231' },
	{ name: 'Teachers of Tomorrow (TOT)', booth: 'F232' },
	{ name: 'TEDxUCIrvine', booth: 'F233' },
	{ name: 'U See Eyes (Pre-Optometry Club)', booth: 'F234' },
	{ name: 'Undergraduate Business Association', booth: 'F235' },
	{ name: 'Undergraduate Finance Association', booth: 'F236' },
	{ name: 'Undergraduate Public Health Association at UCI', booth: 'F237' },
	{ name: 'Women in Leadership at UCIWIL', booth: 'F238' }
];

export const communityService = [
	{ name: 'Alpha Phi Omega', booth: 'F239' },
	{ name: 'American Red Cross Club at UCI', booth: 'F240' },
	{ name: 'Anteater Smile Project at UCI - ASP', booth: 'F241' },
	{ name: 'Anteaters Tzu Ching', booth: 'F242' },
	{ name: "Anteaters' Habitat for Humanity", booth: 'F243' },
	{ name: 'Art Activism', booth: 'F244' },
	{ name: 'Be The Match on Campus', booth: 'F245' },
	{ name: 'Bhagat Puran Singh Health Initiative at UCI', booth: 'F246' },
	{ name: 'Brain Exercise Initiative at UCI', booth: 'F247' },
	{ name: 'By Any Means at UCI', booth: 'F248' },
	{ name: 'Camp Kesem', booth: 'F249' },
	{ name: 'CampMed at UCI', booth: 'F250' },
	{ name: 'Circle K International at UCI', booth: 'F251' },
	{ name: 'End Overdose at UCI', booth: 'F252' },
	{ name: 'Global Medical Brigades [The]', booth: 'F253' },
	{ name: 'Global Refugee Organization Working Towards Health & Hope at UCI', booth: 'F254' },
	{ name: 'Healing Through Humanities', booth: 'F255' },
	{ name: 'Hearts for the Homeless at UC Irvine', booth: 'F256' },
	{ name: 'Made with Love at UCI', booth: 'F257' },
	{ name: 'Medical Educational Missions & Outreach', booth: 'F258' },
	{ name: 'MEDLIFE', booth: 'F259' },
	{ name: 'Prison Education Project at UCI', booth: 'F260' },
	{ name: 'Rotaract at UC Irvine', booth: 'F261' },
	{ name: 'Science Olympiad at UC Irvine', booth: 'F262' },
	{ name: 'Student Healthcare in Practice', booth: 'F263' },
	{ name: 'Students for Global Peacebuilding', booth: 'F264' },
	{ name: 'Teddy Bear Hospital USA at UCI', booth: 'F265' },
	{ name: 'The Patient Project', booth: 'F266' },
	{ name: 'UNICEF at UCI', booth: 'F267' },
	{ name: 'Women and Youth Supporting Each Other (WYSE)', booth: 'F268' }
];

export const peerSupport = [
	{ name: 'Active Minds at UCI', booth: 'F269' },
	{ name: 'Best Buddies at UCI', booth: 'F270' },
	{ name: 'Chinese Union', booth: 'F271' },
	{ name: 'Criminology, Law and Society Club', booth: 'F272' },
	{ name: 'Peers Under Pharmaceutical Sciences', booth: 'F273' },
	{ name: 'PRISM Outreach', booth: 'F274' },
	{ name: 'Public Health Mentorship Program', booth: 'F275' },
	{ name: 'QT STEM', booth: 'F276' },
	{ name: 'Queer & Asian at UCI - Q&A', booth: 'F277' }
];

export const healthAndWellness = [
	{ name: 'Free Clinic Project', booth: 'F278' },
	{ name: 'Health and Justice Advocates at UCI', booth: 'F279' },
	{ name: 'Morning Sign Out at UCI', booth: 'F280' },
	{ name: 'Planned Parenthood Generation Action', booth: 'F281' },
	{ name: 'SWANA Health Alliance', booth: 'F282' }
];

export const environmental = [
	{ name: 'Earth System Science Club', booth: 'G128' },
	{ name: 'In the Green', booth: 'G129' }
];

export const political = [
	{ name: 'Anakbayan UCI', booth: 'H123' },
	{ name: 'Movimiento Estudiantil Chicanx de Aztlan - MEChA', booth: 'G124' },
	{ name: 'CALPIRG - California Public Interest Research Group at UCI', booth: 'G125' },
	{ name: 'College Republicans at UCI (College GOP)', booth: 'G126' }
];

export const hobbiesAndInterests = [
	{ name: 'Amateur Radio Association at UCI - ARA', booth: 'I84' },
	{ name: 'Anime Club at UCI (formerly Anime Community Club at UCI)', booth: 'I85' },
	{ name: 'Cal Animage Epsilon (formerly Anime Club-Cal Animage Epsilon)', booth: 'I86' },
	{ name: 'Anteater Combotics Engineering (ACE) at UCI', booth: 'I87' },
	{ name: 'First-Person View at UCI', booth: 'I88' },
	{ name: 'Personal Electric Vehicles (PEVs) at UCI', booth: 'I89' },
	{
		name: "ZOTBotics' Intoductory Training (ZIT) at UCI (formerly Zotbotics Robotics Club at UCI)",
		booth: 'I90'
	},
	{ name: 'Anteater Photography Organization (APO)', booth: 'I91' },
	{ name: 'Anteater Sim Racing club', booth: 'I92' },
	{ name: 'Anteaters for Animals', booth: 'I93' },
	{ name: 'Anteaters Sprinkling Happiness at UCI', booth: 'I94' },
	{ name: 'B-Boys Anonymous', booth: 'I95' },
	{ name: 'Bike Builders at UCI', booth: 'I96' },
	{ name: 'Birding at UCI - BAU', booth: 'I97' },
	{ name: 'Book Club at UCI', booth: 'H98' },
	{ name: 'Cine-Collective', booth: 'H99' },
	{ name: 'Club Sampling Club at UCI', booth: 'H100' },
	{ name: 'Coffee Friday', booth: 'H101' },
	{ name: 'Creative Writers Guild at UC Irvine', booth: 'H102' },
	{ name: 'Drainers at UCI', booth: 'H103' },
	{ name: 'Fashion and Sneakers at UCI -FS at UCI', booth: 'H104' },
	{ name: 'Fighting Gamers at UCI', booth: 'H105' },
	{ name: 'Furries at UCI', booth: 'H106' },
	{ name: 'Genetic Counseling Special Interest Group at UCI', booth: 'H107' },
	{ name: 'Hiking Club at UCI', booth: 'H108' },
	{ name: 'Irvine Chess Club', booth: 'H109' },
	{ name: 'Keebs Club at UCI', booth: 'H110' },
	{ name: 'Music Education for the Underserved - MeU', booth: 'H111' },
	{ name: 'osu! at UCI', booth: 'H112' },
	{ name: 'REV Auto Car Club', booth: 'H113' },
	{ name: 'Ski and Snowboard Club', booth: 'H114' },
	{ name: 'Swing Dance at UCI', booth: 'H115' },
	{ name: 'Sword at UCI - Belegarth Medieval Combat Society', booth: 'H116' },
	{ name: 'The Antweavers', booth: 'H117' },
	{ name: 'The Fear-Eaters at UCI - TFEUCI', booth: 'H118' },
	{ name: 'Themed Entertainment Association @ UCI', booth: 'H119' },
	{ name: 'Unmanned Aerial Vehicles at UCI (formerly UAVs at UCI)', booth: 'H120' },
	{ name: 'We (Skin)Care at UCI', booth: 'H121' },
	{ name: 'Yugioh Club at UCI', booth: 'H122' }
];
